.gitignore
lib/types.d.ts
src/app/api/events/byDate/route.ts
src/app/api/events/route.ts
src/app/events/page.tsx
src/components/Events/Calendar.tsx
src/components/Events/CalendarBody.tsx
src/components/Events/UpcomingEvents.tsx

Adds an environment variable to fetch from google calendar. Add `.env` and `CALENDAR_API_KEY` as one of the entries

Update the calendar to fetch data

---

src/components/Divisions/Shared/Navigator.tsx

Updated styling so that the navigator doesn't take up the whole screen width

Navigator width

---

config/about.config.ts
config/hack.config.ts
config/officers.config.ts

feat: Add data for hackutd

---

config/home.config.ts
lib/types.d.ts
src/app/page.tsx

Add distinctions between the different tiers

Tier distinctions

---

config/about.config.ts
config/board.config.ts
config/development.config.ts
config/industry.config.ts
config/officers.config.ts

Changes made in this PR: 
- Added ACM Development data
- Added board members into Officers page
- Added Director of Industry into Industry section of Officers page

feat: updated dev data + officers page

---

src/components/Events/EventTime.tsx
src/components/Events/UpcomingEvents.tsx

When server rendering it provided UTC timestamps which wasn't super useful

Client render dates

---

config/about.config.ts

i changed the branch name but this one is good to go.

changed lorem ipsum text on about page

---

src/app/page.tsx
src/components/About/DivisionCard.tsx
src/components/Apply/ApplyPrograms.tsx
src/components/Divisions/Shared/DivisionHeader.tsx

Added rounded edges and an outline on the buttons to match the website's style.

(#69) rounded edges & outline on buttons

---

config/about.config.ts

ACM Development: ACM Development is dedicated to designing, building, and maintaining robust web applications and infrastructures that support ACM’s interactions with its members. Key projects include the Member Portal, which streamlines member engagement, and UTD Grades, a resource for academic insights. By ensuring the reliability and functionality of these platforms, ACM Development plays a crucial role in enhancing the member experience and fostering a connected community.
ACM Research: ACM Research is an undergraduate program designed to immerse students in the world of research by providing essential skills, resources, and mentorship. The program empowers participants to develop nuanced ideas, engage in hands-on research, and prepare for potential academic publications. From …

edited division descriptions

---

src/components/Divisions/Shared/DivisionHeader.tsx

Apply links now lead to the spring 25 application forms for all divisions.

updated all divisions' apply links for s25

---

config/industry.config.ts

updated officers (pictures needed)

---

src/components/About/Divisions.tsx

Center ACM Industry and ACM Community

---

config/home.config.ts
src/app/page.tsx

updated sponsors

---

src/components/About/AboutHeader.tsx
src/components/Button.tsx

Update about page header text

---

config/about.config.ts
config/divisions.config.ts
config/media.config.ts
src/app/[...slug]/page.tsx
src/components/Divisions/Media/MediaHeader.tsx
src/components/Divisions/Shared/DivisionHeader.tsx
src/components/Divisions/Shared/Navigator.tsx
src/components/Divisions/Shared/divisionUtil.ts

feat: create media page

---

components.json
package-lock.json
package.json
src/app/globals.css
src/app/page.tsx
src/components/Home/Sponsor.tsx
src/components/Home/SponsorCarousel.tsx
src/components/ui/button.tsx
src/components/ui/carousel.tsx
src/lib/utils.ts
tailwind.config.ts

https://github.com/user-attachments/assets/efb82ad0-4fa6-463f-a181-ee9d142c8dc5

feat: update sponsor images to be in a carousel

---

src/app/[...slug]/page.tsx
src/app/apply/page.tsx
src/app/page.tsx
src/components/Apply/ApplyHeader.tsx
src/components/Apply/ApplyProgramCard.tsx
src/components/Apply/ApplyPrograms.tsx
src/components/Button.tsx
src/components/Divisions/Industry/IndustrySponsors.tsx
src/components/Divisions/Shared/DivisionExperience.tsx
src/components/Divisions/Shared/DivisionFAQ.tsx
src/components/Divisions/Shared/DivisionHeader.tsx
src/components/Divisions/Shared/DivisionOfficers.tsx
src/components/Divisions/Shared/DivisionsCarousel.tsx
src/components/Divisions/Shared/Navigator.tsx
src/components/Divisions/Shared/QuoteMarks.tsx
src/components/Divisions/Shared/WinningProjects.tsx
src/components/Divisions/Shared/WorkShops.tsx
src/components/Divisions/Shared/divisionUtil.ts
src/components/Footer.tsx
src/components/Home/SponsorCarousel.tsx
src/components/parallaxImages.tsx
src/components/ui/carousel.tsx

feat: mobile now actually works

---

src/components/Home/Navbar.tsx

Mobile now always has a background

fix: update navbar styles for responsive background opacity

---

src/components/About/DivisionCard.tsx

- Only using popover to handle additional links

refactor: simplify link handling in DivisionCard component

---

src/app/api/events/route.ts

Fix some issues when filtering dates

fix: adjust time zone handling for calendar event API requests

---

lib/types.d.ts
src/app/api/events/past/route.ts
src/app/api/events/route.ts
src/components/Events/EventDays.tsx
src/components/Events/PastEvents.tsx

feat: add event description for past events and in the calendar popups

---

src/components/Events/PastEventTime.tsx
src/components/Events/PastEvents.tsx

I HATE TIMEZONES
I HATE TIMEZONES
I HATE TIMEZONES
I HATE TIMEZONES
I HATE TIMEZONES
I HATE TIMEZONES
I HATE TIMEZONES

fix: incorrect time zone for past events

---

config/development.config.ts
config/hack.config.ts

hack officers have been updated, some of the images are missing but we can get those after they do hack pics
Also some dev officers were updated

Hack Officers updated + some dev officers updated

---

src/components/Home/EventCarousel.tsx
src/components/Home/FlexCarousel.tsx
src/components/Home/Navbar.tsx

Add better styling for the landing page on mobile

Mobile stying

---

package-lock.json
package.json
src/app/api/events/route.ts
src/app/layout.tsx
src/components/Events/UpcomingEvents.tsx
src/components/QueryProvider.tsx

move to react query and use timezone when fetching upcoming events

---

src/components/Officers/OfficerGrid.tsx

we're not limiting the size of images which results in large payloads in the officer page. This should limit that :)

add sizes and limit size of images 
